"""Build the study-design figure.

The figure is TikZ, not matplotlib: it carries typeset mathematics and reads as
a drawn diagram rather than a plot, which is what this kind of figure has to be.
Everything in it is drawn by hand except the cohort sizes, which are read from
the result files here and written to fig_design_data.tex, so the figure cannot
advertise a cohort the repository does not contain.

    python paper/make_design_figure.py
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# Planned cohort sizes, used only when the result file is absent so that a
# fresh clone still builds a sensible figure.
PLANNED = {"NPhys": 104, "NBci": 9, "NCho": 52}
SOURCES = {
    "NPhys": ["raw_folds_motor8_q4.csv", "raw_folds_refstate_motor8_q4.csv"],
    "NBci": ["raw_folds_bci2a_motor8_q4.csv",
             "raw_folds_refstate_bci2a_motor8_q4.csv"],
    "NCho": ["raw_folds_refstate_cho2017_motor8_q4.csv",
             "calib_folds_calib_cho_b0?.csv"],
}


def n_subjects(res: Path, patterns: list[str]) -> int | None:
    for pat in patterns:
        hits = sorted(res.glob(pat))
        if not hits:
            continue
        try:
            d = pd.concat([pd.read_csv(h, usecols=["subject"]) for h in hits],
                          ignore_index=True)
        except (ValueError, KeyError, pd.errors.EmptyDataError):
            continue
        if len(d):
            return int(d.subject.nunique())
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--results", default=str(ROOT / "results"))
    ap.add_argument("--out", default=str(ROOT / "results" / "figures"))
    args = ap.parse_args(argv)
    res, out = Path(args.results), Path(args.out)

    counts = {}
    for key, patterns in SOURCES.items():
        n = n_subjects(res, patterns)
        counts[key] = n if n else PLANNED[key]
        print(f"  {key:6s} {counts[key]:4d}"
              + ("" if n else "   (planned; no result file yet)"))
    (HERE / "fig_design_data.tex").write_text(
        "%% AUTO-GENERATED by paper/make_design_figure.py: DO NOT EDIT.\n"
        + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in counts.items()),
        encoding="utf-8")

    build = HERE / "build"
    build.mkdir(parents=True, exist_ok=True)
    r = subprocess.run(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
         "-output-directory", str(build), "fig_design.tex"],
        cwd=HERE, capture_output=True, text=True)
    if r.returncode or not (build / "fig_design.pdf").exists():
        print(r.stdout[-3000:])
        print("pdflatex failed")
        return 1
    out.mkdir(parents=True, exist_ok=True)
    shutil.copy2(build / "fig_design.pdf", out / "fig_design.pdf")
    print(f"wrote {out / 'fig_design.pdf'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
